data:
  augname: ft
  cache: true
  cutmix_alpha: 0
  data_dir: null
  ds_name: cifar10
  ibase: 128
  mixup_alpha: 0
  multiclass: false
  num_classes: 10
  ra_num_layers: 2
  ram: 0
  resize: null
  splits:
    eval:
      files: val*
      num_images: 10000
      slice: ''
      tfds_split: test
    minival:
      files: train*
      num_images: 10000
      slice: ''
      tfds_split: test
    train:
      files: train*
      num_images: 50000
      slice: ''
      tfds_split: train
    trainval:
      files: train*
      num_images: 1281167
      slice: !!python/object/apply:builtins.slice
      - 0
      - null
      - null
      tfds_split: null
  tfds_name: cifar10
  tfds_split: null
  try_gcs: true
eval:
  batch_size: 8
  isize: 224
  split: null
model:
  act_fn: silu
  blocks_args:
  - conv_type: 1
    expand_ratio: 1
    input_filters: 32
    kernel_size: 3
    num_repeat: 1
    output_filters: 16
    se_ratio: null
    strides: 1
  - conv_type: 1
    expand_ratio: 4
    input_filters: 16
    kernel_size: 3
    num_repeat: 2
    output_filters: 32
    se_ratio: null
    strides: 2
  - conv_type: 1
    expand_ratio: 4
    input_filters: 32
    kernel_size: 3
    num_repeat: 2
    output_filters: 48
    se_ratio: null
    strides: 2
  - conv_type: 0
    expand_ratio: 4
    input_filters: 48
    kernel_size: 3
    num_repeat: 3
    output_filters: 96
    se_ratio: 0.25
    strides: 2
  - conv_type: 0
    expand_ratio: 6
    input_filters: 96
    kernel_size: 3
    num_repeat: 5
    output_filters: 112
    se_ratio: 0.25
    strides: 1
  - conv_type: 0
    expand_ratio: 6
    input_filters: 112
    kernel_size: 3
    num_repeat: 8
    output_filters: 192
    se_ratio: 0.25
    strides: 2
  bn_epsilon: 0.001
  bn_momentum: 0.9
  bn_type: null
  conv_dropout: null
  data_format: channels_last
  depth_coefficient: 1.0
  depth_divisor: 8
  dropout_rate: 1.0e-06
  feature_size: 1280
  gn_groups: 8
  headbias: null
  local_pooling: false
  min_depth: 8
  model_name: efficientnetv2-b0
  num_classes: 10
  survival_prob: 0.8
  width_coefficient: 1.0
runtime:
  iterations_per_loop: 1000
  keep_checkpoint_every_n_hours: 5
  keep_checkpoint_max: 5
  log_step_count_steps: 64
  mixed_precision: true
  skip_host_call: false
  strategy: null
  use_async_checkpointing: false
train:
  batch_size: 512
  ema_decay: 0.9996
  epochs: 15
  ft_init_ckpt: null
  ft_init_ema: true
  gclip: 0
  isize: 1.0
  label_smoothing: 0.1
  loss_type: null
  lr_base: 0.0005
  lr_decay_epoch: 2.4
  lr_decay_factor: 0.97
  lr_min: 0
  lr_sched: constant
  lr_warmup_epoch: 1
  min_steps: 10000
  optimizer: rmsprop
  sched: true
  split: null
  stages: 0
  varsexp: null
  weight_decay: 1.0e-05
  weight_decay_exclude: .*(bias|gamma|beta).*
  weight_decay_inc: 0.0
